version: '3'

services:
  express-oo:
    container_name: express-oo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env

  minio:
    container_name: minio
    image: bitnami/minio:latest
    restart: always
    environment:
      - "MINIO_ROOT_USER=yourusername"
      - "MINIO_ROOT_PASSWORD=passatleast5char"
    ports:
      - "9000:9000"
      - "9001:9001"
